### ISSUE TITLE
Missing fixes for computer without KOOMPI repo

### ISSUE THREAD

**Issue by IsaacJReay** [koompi/os-upgrade#2]
Some of the packages that are needed to be installed are from KOOMPI repo and computer without this repo will fail at smart_install() because it cannot find ttf_* and other pakages.

**Comment by mrrbrilliant** [comment]
So what is your ideal solution?

**Comment by IsaacJReay** [comment]
The easiest way is to overwrite the pacman.conf with a template everytimes the script start

Template:
[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
VerbosePkgLists
ParallelDownloads = 5
SigLevel    = Never
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[koompi]
SigLevel = Never
Server = http://dev.koompi.org/koompi

**Comment by IsaacJReay** [comment]
Or, we could make template files of all configs and wrap in tar and then just extract them all with root permission into /

**Comment by mrrbrilliant** [comment]
Brought back insert KOOMPI repo function in this commit [ddfcde4](https://github.com/koompi/os-upgrade/commit/ddfcde4efa976aaa3da5d1df3c43e35666944d95).
